const { app, BrowserWindow } = require("electron");
const path = require("path");
const { spawn } = require("child_process");
const getPort = require("get-port");

let mainWindow;
let nextServerProcess;

const isDev = !app.isPackaged;

async function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, "preload.js"),
    },
  });

  if (isDev) {
    // In development, load the URL where 'next dev' is running
    mainWindow.loadURL("http://localhost:3000");
    mainWindow.webContents.openDevTools();
  } else {
    // In production, start the bundled Next.js server
    const port = await startNextJSServer();
    mainWindow.loadURL(`http://localhost:${port}`);
  }

  mainWindow.on("closed", () => {
    mainWindow = null;
  });
}

async function startNextJSServer() {
  const port = await getPort();
  
  // Path to the standalone server.js generated by 'next build'
  // In production, this is copied to the resources folder
  const serverPath = path.join(process.resourcesPath, "standalone", "server.js");
  
  console.log("Starting local Next.js server at:", serverPath);

  nextServerProcess = spawn(process.execPath, [serverPath], {
    env: {
      ...process.env,
      PORT: port.toString(),
      HOSTNAME: "localhost",
      NODE_ENV: "production",
    },
  });

  nextServerProcess.stdout.on("data", (data) => {
    console.log(`Next.js: ${data}`);
  });

  nextServerProcess.stderr.on("data", (data) => {
    console.error(`Next.js Error: ${data}`);
  });

  // Give the server a moment to start
  await new Promise((resolve) => setTimeout(resolve, 2000));
  
  return port;
}

app.on("ready", createWindow);

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("will-quit", () => {
  // Kill the Next.js server child process when Electron quits
  if (nextServerProcess) {
    nextServerProcess.kill();
  }
});